config/routes.rb
BtDemo::Application.routes.draw do

  match "users/sign_in" =>"sessions#new", :as => :sign_in , :via => :get
  match "users/login" =>"sessions#create" , :via => :post
  match "sessions/destroy" =>"sessions#destroy",:as => :sign_out , :via => :get

  match 'about_me' => 'home#about', :as => :about_me ,:via => :get
  match 'friends' => 'home#friends', :as => :friends ,:via => :get
  match 'login_out' => 'home#login_out', :as => :login_out ,:via => :get
 
  resources :posts
  resources :users

  root :to => 'home#index'

end

app/models/post.rb
#encoding:utf-8
class Post < ActiveRecord::Base
  attr_accessible :content, :name,:tag
  validates :name ,:uniqueness => { :message => "标题已存在." },
                   :length => { :minimum => 2 , :message =>"#标题不能少于2个字符."}
  validates :tag ,:length => { :minimum => 2 , :message =>"#关键字不能少于2个字符."}

  paginates_per 5

  def all_tags
  	 tag.nil??  [] : tag.split(/,|，|\s+/)
  end

  def post_next(order="inc")
  	order== "inc"? Post.where("id < #{id}").last : Post.where("id > #{id}").first
  end

  def last_post
  	
  end
  
end

app/models/user.rb
class User < ActiveRecord::Base

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

  attr_accessible :email, :name, :password, :password_confirmation
  has_secure_password

  validates :name, presence: true, length: { maximum: 25 }
  validates :email, presence: true, 
                format: { with: VALID_EMAIL_REGEX }, 
                uniqueness: { case_sensitive: false }
  validates :password, presence: true, length: { minimum: 6 }
  validates :password_confirmation, presence: true

  before_save { |user| user.email = email.downcase }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  include ApplicationHelper
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  
  def index
  	session[:index] = 1
  end
  
  def about
  	session[:index] = 4
  end

  def friends
  	session[:index] = 3
  end

  def login_out
  	session[:admin] = nil
  	session[:index] = 1
  	redirect_to root_path
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  # http_basic_authenticate_with :name => "songjiayang", :password => "songjiayang", :except => [:index, :show,:posts_with_tag]
  before_filter :save_session, :only => [:create, :update,:destroy,:new,:edit]

  def index
    if params[:tag].blank?
      @posts = Post.order("created_at desc").page params[:page]
    else
      @posts = Post.where(["tag like ?",'%'+params[:tag].to_s.strip+'%']).order(:created_at).page params[:page]
    end
    session[:index] = 2
  end

  def show
    @post = Post.find(params[:id])
    @pre_page = @post.post_next('inc')
    @next_page = @post.post_next('desc')
  end

  def new
    @post = Post.new
  end

  def edit
    @post = Post.find(params[:id])
  end

  def create
    @post = Post.new(params[:post])
    respond_to do |format|
      if @post.save
        BlogMailer.report_new_one_blog(@post.id).deliver!
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render json: @post, status: :created, location: @post }
      else
        format.html { render action: "new" }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @post = Post.find(params[:id])

    respond_to do |format|
      if @post.update_attributes(params[:post])
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy

    respond_to do |format|
      format.html { redirect_to posts_url }
      format.json { head :no_content }
    end
  end

  private 
  def save_session
    redirect_to sign_in_path unless current_user
  end
end

app/controllers/sessions_controller.rb
#encoding:utf-8

class SessionsController < ApplicationController

  def new
  	@user = User.new
  	session[:index] = 5
  end

  def create
  	@user = User.find_by_email(params[:user][:email])
  	if @user 
  		if @user.authenticate(params[:user][:password])
  			session[:user_id] = @user.id
  			redirect_to posts_path
  		else
  			flash[:password_error] = "密码输入错误"
  			redirect_to sign_in_path
  		end
  	else
       flash[:mail_error] = "输入用户不存在"
       redirect_to sign_in_path
  	end
  end

  def destroy
  	session[:user_id] = nil
  	redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
  end

  def new
  end

  def create
  end

  def edit
  end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
	
	def current_user
  	User.find_by_id(session[:user_id])
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
#encoding:utf-8

module PostsHelper
	def time_strf_china(post)
		post.updated_at.localtime.strftime("%F %R")
	end

	def fast_view(post,number)
		if post.content.size>number
			"#{post.content.first(number)}........" 
		else
			post.content
		end
	end

	def post_error(post,attr_name)
		if @post.errors[attr_name].blank?
			attr_name=="name"? '标题必须唯一.' : '关键字以逗号,空格分隔.'
       	else
       	  error_msg = ""
       	 @post.errors[attr_name].each {|msg| error_msg+=msg}
       	 error_msg
       	end
			
	end
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/_top.html.erb
      <ul class="nav nav-pills pull-right">
          <li <%if session[:index] ==1%>class="active"<%end%>><%=link_to "主页" , root_path %></li>
          <li <%if session[:index] ==2%>class="active"<%end%>><%=link_to "博客" , posts_path %></li>
          <li <%if session[:index] ==3%>class="active"<%end%>><%=link_to "朋友",friends_path%></li>
          <li <%if session[:index] ==4%>class="active"<%end%>><%=link_to "关于", about_me_path%></li>
        <%if current_user %>
        <li ><%=link_to "退出", sign_out_path%></li>
        <%else%>
        <li <%if session[:index] ==5%>class="active"<%end%>>
          <%=link_to "登录", sign_in_path%></li>
        <%end%>
        </ul>
     <h3 class="muted">静坐常思已过，闲谈莫论人非</h3>

app/views/home/index.html.erb
<% cache do %>
      <div class="jumbotron">
      	<div>
      		<img src="/images/001.png ">	
      	</div>
        <p class="lead">Cras justo odio, dapibus ac facilisis in, egestas eget quam. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus.</p>
      </div>

      <div class="row-fluid marketing">
        <div class="span6">
          <h4>团结</h4>
          <p>Donec id elit non mi porta gravida at eget metus. Maecenas faucibus mollis interdum.</p>

          <h4>协作</h4>
          <p>Maecenas sed diam eget risus varius blandit sit amet non magna.</p>
        </div>

        <div class="span6">
          <h4>创新</h4>
          <p>Donec id elit non mi porta gravida at eget metus. Maecenas faucibus mollis interdum.</p>

          <h4>我们最牛</h4>
          <p>Morbi leo risus, porta ac consectetur ac, vestibulum at eros. Cras mattis consectetur purus sit amet fermentum.</p>
        </div>
      </div>

<%end%>

    

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>小鱼驿站</title>
    <link href="/images/favicon.png" rel="icon">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">
    <%= stylesheet_link_tag    "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->

    <!-- Fav and touch icons -->
  </head>

  <body>
    <div class="container-narrow">
      <div class="masthead">
        <%=render 'home/top'%>
      </div>
      <hr>
      <%=yield%>
      <hr>
      <div class="footer">
          <p class="pull-center">sjy &copy; Company 2012</p>
      </div>

    </div> 
  </body>
</html>

app/views/layouts/blog_mailer.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>小鱼驿站</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">
    <%= stylesheet_link_tag    "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->

    <!-- Fav and touch icons -->
  </head>

  <body>
    <div class="container-narrow">
      <hr>
      <%=yield%>
      <hr>
      <div class="footer">
        <p>sjy &copy; Company 2012</p>
      </div>

    </div> 
  </body>
</html>

app/views/posts/_form.html.erb
<div class="field">
  <%= f.label :标题 %>
   <%= f.text_field :name, :class => 'text_field' %>
    <span class="help-inline"><font color="red"><%=post_error(@post,"name")%></font></span>
</div>
 <div class="field">
    <%= f.label :关键词 %>
    <%= f.text_field :tag %>
     <span class="help-inline"><font color="red"><%=post_error(@post,"tag")%></font></span>
</div>
 <div class="field">
    <%= f.label :内容 %>
    <%= f.kindeditor :content, :width => 700, :height => 300 %>
</div>
<div class="form-actions">
  <button class="btn btn-success" type="submit">保存</button> or
	<%= link_to "取消", posts_path %>
</div>

app/views/posts/_posts.html.erb
<% @posts.each do |post| %>
<div class="hero-unit">
  <h2><%= link_to post.name, post_path(post) %></h2>
 
   <p><%= raw fast_view post,500%></p>     
    <h4>
      <%post.all_tags.each do |tag|%>
      <%=link_to tag,:controller => "posts", :action => "index", :tag => tag%> .
      <%end%>
    &nbsp;&nbsp;
      <%unless current_user%>
          <%=time_strf_china post%>
      <%else%>
          <%= link_to "修改", edit_post_path(post), :class => 'btn btn-primary' %>
          <%= link_to "删除", post_path(post), :method => "delete", :confirm => "#{t("web-app-theme.confirm", :default => "Are you sure?")}", :class => 'btn btn-danger' %>
      <%end%>
  </h4>
</div>
<% end %>

app/views/posts/edit.html.erb
<%= form_for @post, :url => post_path(@post), :html => { :class => "edit_post", :id => "edit_post" } do |f| -%>
  <input name="_method" type="hidden" value="put" />
  <%= render :partial => "form", :locals => {:f => f} %>
<% end -%>

app/views/posts/index.html.erb
<%=render "posts"%>
<div><%= paginate @posts%></div>

app/views/posts/new.html.erb
<%= form_for @post, :class=>"well",:url => posts_path, :html => { :class => :form } do |f| -%>
  <%= render :partial => "form", :locals => {:f => f} %>
<% end -%>

app/views/posts/show.html.erb
<h1 style="text-align:center;"><%=@post.name%></h1><br/>
<div class="show_text"><%= raw @post.content %></div>
<ul class="pager">
  <li class="previous">
  	<%if @pre_page%>
      <a href="/posts/<%=@pre_page.id%>">&larr; 上一篇</a>
    <%else%>
      <%=link_to "返回",posts_path%>
    <%end%>
  </li>
  <li class="next">
  	<%if @next_page%>
    	<a href="/posts/<%=@next_page.id%>">下一篇 &rarr;</a>
    <%else%>
    	<%=link_to "返回",posts_path%>
    <%end%>
  </li>
</ul>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/edit.html.erb
<h1>Users#edit</h1>
<p>Find me in app/views/users/edit.html.erb</p>

app/views/users/new.html.erb
<h1>Users#new</h1>
<p>Find me in app/views/users/new.html.erb</p>

app/views/users/show.html.erb
<h1>Users#show</h1>
<p>Find me in app/views/users/show.html.erb</p>